spring:
  profiles:
    active: default
  cloud:
    gcp:
      project-id: neural-medium-289511
      pub-sub:
        dataflow-json-processing-topic-name: projects/neural-medium-289511/subscriptions/hamster