spring:
  cloud:
    gcp:
      credentials:
        location: file:C:\hamster\neural-medium-289511-140046913ebc.json
#        location: file:/Users/roman.drohobytskyy/IdeaProjects/GCP-pub-sub-key.json