spring:
  profiles:
    active: default
  cloud:
    gcp:
      project-id: mineral-beaker-328507
      pub-sub:
        dataflow-topic: "hamster"
scheduling:
  hamsters:
    valid:
      initialDelay: 0
      fixedRate: 5000
    invalid:
      initialDelay: 1000
      fixedRate: 20000